### ISSUE TITLE
scTDA tutorial link not working

### ISSUE THREAD

**Issue by bioinformaticss** [pcamara/scTDA#3]
Hi Pablo, 

Congrats on the publication of your nice work on scTDA. I am interested in analyze some of my data with it. When I look through your tutorial, I found, however, the link to the source notebook and data files is no longer existed. Could you please update it? 

Also, does your software has to have a Ayasdi account? Do you have a tutorial to run your motor neuron data with the free available mapper? 

Thanks

**Comment by pcamara** [comment]
Hi,

Thank you! I have fixed the broken link to the tutorial files. 

The software does not require having an Ayasdi account. In that case, it uses an open-source implementation of the Mapper algorithm. In the next months (time allowing), I want to improve substantially the open-source implementation and add some extra features. Unfortunately, I do not have a tutorial based on our motor-neuron data and the open-source implementation of Mapper. If I get some time, I may prepare one in the future.
