### ISSUE TITLE
Data input

### ISSUE THREAD

**Issue by kobeho24** [pcamara/scTDA#7]
Hi pcamara,
I am new to bioinformatics, I came across your nature biotech paper and found the scTDA seemed to be very useful for single-cell analysis, at least the topological stuff makes more sense than current packages. Just wonder, if all I have is a gene expression matrix in which rows correspond to genes and  columns correspond to cells, with first row of cell ids and first column for gene ids. How can I input the matrix to scTDA pre-process function?

Best!
Gary

**Comment by pcamara** [comment]
Hi,
You may have a look at the [tutorial](https://www.dropbox.com/s/ma80a641miteyxf/scTDA%20Tutorial.tar.gz?dl=0) that accompanies scTDA. There you can look at the input files to see an example of how the input data should be formatted. If your data is not in that format, you should put it into that format before using scTDA. You may be also interested in looking at some of the files that are generated at intermediate steps, e.g. those containing normalized expression values, in case your data is already normalized.

**Comment by kobeho24** [comment]
Having a normalized gene expression matrix is exactly my case. And I have the differential expressed gene list as well. I tried to modify all my file to fit the file format in the tutorial, But I still have questions.
1. Is there any way to disable the TPM normalization in the pre-process module? Cuz I don't fully agree with applying RPKM/FPKM/TPM on single-cell analysis.
2. Even though I can format my file to fit scTDA, but I don't know how can I assign my DE gene list to the variable scTDA.Preprocess.which.genes, since it seems to be not shown in the variable list, can I simply do scTDA.Preprocess.which.genes = [gene list array]?

Best!

**Comment by pcamara** [comment]
You can use your own normalization, preprocessing, and selected genes in scTDA. You must skip the Preprocess step and follow the pipeline starting on the TopologicalRepresentation step. To that end, you need to generate two tables with your normalized/preprocessed data: name_of_your_project.mapper.tsv and name_of_your_project.all.tsv. The first table is used to build the topological representation, and the second one contains the features that will be evaluated on the topological representation. You can see the format of these tables in the example of the tutorial.

**Comment by kobeho24** [comment]
For the second table you mentioned, in tutorial it has over 26k genes, it should not be the selected genes. In my case, what should I put into that particular table, only selected? And for the mapper table, I guess it should only be the expression values without row name or column name.

**Comment by pcamara** [comment]
The second table contains all the features whose localization will be evaluated on the representation. E.g. all the genes. The first table contains only selected genes used for building the mapper representation.

**Comment by kobeho24** [comment]
In topological representation part of the tutorial, any specific reason for the choice for the number of patches and their overlap (25X25 bins w/ 40% overlap)? How should I determine the right parameter choice in my real data? I noticed that in Supp. Fig.12 it says that different parameter choices shows a large degree of consistency, but I still wonder how can I get the optimal parameters.

**Comment by pcamara** [comment]
You could use some proxy (e.g. in a sample from a tumor, separation between normal and tumor cells). 

We are developing more quantitative ways of finding optimal parameters.
